CREATE TABLE Rooms(ID INT PRIMARY KEY AUTO_INCREMENT, NUMB INT,
  CATEGORY VARCHAR(100), PRICE INT);

CREATE TABLE Booked(ID INT PRIMARY KEY AUTO_INCREMENT, NUMB INT,
  CHECK_IN DATE, CHECK_OUT DATE, ADDITION_OPTION VARCHAR(100), TOTALPRICE INT, USER VARCHAR(100));

CREATE TABLE Users(ID INT PRIMARY KEY AUTO_INCREMENT, FIRST_NAME VARCHAR(100), LAST_NAME VARCHAR(100),
  NICKNAME VARCHAR(100));
