CREATE TABLE Rooms(ID INT PRIMARY KEY AUTO_INCREMENT, NUMB INT,
  CATEGORY VARCHAR(100), PRICE INT);

CREATE TABLE Booked(ID INT PRIMARY KEY AUTO_INCREMENT, NUMB INTEGER not NULL ,
  CHECK_IN DATE NOT NULL , CHECK_OUT DATE NOT NULL , ADDITION_OPTION VARCHAR(100) NOT NULL ,
  TOTALPRICE INT NOT NULL , USER VARCHAR(100) NOT NULL );

CREATE TABLE Users(ID INT PRIMARY KEY AUTO_INCREMENT, FIRST_NAME VARCHAR(100), LAST_NAME VARCHAR(100),
  NICKNAME VARCHAR(100) NOT NULL );
